### ISSUE TITLE
Some questions about datasets and preprocessing

### ISSUE THREAD

**Issue by yyysjz1997** [TheDatumOrg/VUS#1]
Many thanks for your work and repo. I learned a lot. I am wondering about the datasets and their preprocessing.

Such as the MSL dataset, there are many data files in the corresponding folder, but a single file is a single variable data, i.e. the first dimension is X and the second dimension is label. But as far as I know, the MSL dataset has 55 dimensions. So I would like to know whether your work is univariate anomaly detection. Is there any further preprocessing?

**Comment by boniolp** [comment]
Thank you for your interest in our research work. For NASA-SMAP and NASA-MSL, as you mentioned correctly, these are two real spacecraft telemetry data (multivariate) with anomalies from Soil Moisture Active Passive (SMAP) satellite and Curiosity Rover on Mars (MSL). We only keep the first data dimension that presents the continuous data, and we omit the remaining dimensions with binary data.

You may find more information on the benchmark here:
https://www.vldb.org/pvldb/vol15/p1697-paparrizos.pdf
