### ISSUE TITLE
Pip install doesn't work

### ISSUE THREAD

**Issue by Blackandwhite23** [TheDatumOrg/VUS#3]
When I use "pip install vus" and try the sample code I get the following message:
"ImportError: cannot import name 'get_metrics' from 'vus.metrics' (.\envs\test-vus\lib\site-packages\vus\metrics.py)"
When I check the file mentioned above I see, that the source code looks different than in this repo. It only contains:

`from .utils.metrics import metricor
from .analysis.robustness_eval import generate_curve

def get_range_vus_roc(score, labels, slidingWindow):
    grader = metricor()
    R_AUC_ROC, R_AUC_PR, _, _, _ = grader.RangeAUC(labels=labels, score=score, window=slidingWindow, plot_ROC=True)
    _, _, _, _, _, _,VUS_ROC, VUS_PR = generate_curve(labels, score, 2*slidingWindow)
    metrics = {'R_AUC_ROC': R_AUC_ROC, 'R_AUC_PR': R_AUC_PR, 'VUS_ROC': VUS_ROC, 'VUS_PR': VUS_PR}

    return metrics`

The function "get_metrics" doesn't exist. If I copy the files manually into the folder, the sample codes works.
I hope I did nothing wrong during installation. 
Also I had compatability issues with my other code, it needs special versions of scikit-learn and also a special python version (like mentioned in this repo). But in this case it doesn't run together with other packages like pyod. I will try to use the evaluation in another program installed in a virtual environment.

**Comment by bogireddytejareddy** [comment]
I have updated the pip package with latest version of the code. Installing version 0.0.3 should help with the error.
